version: '3.8'
services:
  mongo:
    image: mongo
    volumes: 
      - /mnt/mongo-data:/data/db
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - app-data:/starter
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
    links:
      - mongo
    depends_on:
      - mongo

volumes:
  app-data:
    driver: local
